test cloudbox

diff --git a/bin/cloudbox b/bin/cloudbox
--- a/bin/cloudbox
+++ b/bin/cloudbox
@@ -15,6 +15,18 @@ do
     esac
 done
 
+if [ ! -x "$(which docker)" ]
+then
+    echo "docker is not available in this shell"
+    exit 1
+fi
+
+if ! docker run --rm hello-world | grep -q "Hello from Docker!"
+then
+    echo "docker hello-world failed"
+    exit 1
+fi
+
 dir="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
 extension="$(basename "${BASH_SOURCE[0]}")"
 if [ "$tag" = "" ]
diff --git a/bin/test-ops b/bin/test-ops
--- a/bin/test-ops
+++ b/bin/test-ops
@@ -2,17 +2,38 @@
 
 dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )"/.. &> /dev/null && pwd )"
 
-if docker run --rm  -v "$dir:/app" alpine:3 sh -c 'apk add --update bash && bash -c "cd /app; . ./ops; bash -c \"cd /; ops dir\""' | egrep -q "^/app$"
+if ! docker run --rm hello-world | grep -q "Hello from Docker!"
 then
-  echo "bash ops ok."
+    echo "docker hello-world failed."
+    exit 1
 fi
 
-if docker run --rm  -v "$dir:/app" alpine:3 sh -c 'apk add --update zsh && zsh -c "cd /app; . ./ops; cd /; ops dir"' | egrep -q "^/app$"
+ok=true
+
+if ! docker run --rm  -v "$dir:/app" alpine:3 sh -c 'apk add --update bash && bash -c "cd /app; . ./ops; bash -c \"cd /; ops dir\""' | egrep -q "^/app$"
 then
-  echo "zsh ops ok (no subshell -- unsupported by zsh)."
+    echo "bash ops failed"
+    docker run --rm  -v "$dir:/app" alpine:3 sh -c 'apk add --update bash && bash -c "cd /app; . ./ops; bash -c \"cd /; ops dir\""'
+    ok=false
 fi
 
-if docker run --rm  -v "$dir:/app" alpine:3 sh -c 'apk add --update loksh && ksh -c "cd /app; . ./ops; cd /; ops dir"' | egrep -q "^/app$"
+if ! docker run --rm  -v "$dir:/app" alpine:3 sh -c 'apk add --update zsh && zsh -c "cd /app; . ./ops; cd /; ops dir"' | egrep -q "^/app$"
 then
-  echo "ksh ops ok (no subshell -- unsupported by ksh)."
+    echo "zsh ops failed (subshell untested -- unsupported by zsh)."
+    ok=false
 fi
+
+if ! docker run --rm  -v "$dir:/app" alpine:3 sh -c 'apk add --update loksh && ksh -c "cd /app; . ./ops; cd /; ops dir"' | egrep -q "^/app$"
+then
+    echo "ksh ops failed (subshell untested -- unsupported by ksh)."
+    ok=false
+fi
+
+if [ $ok = true ]
+then
+    echo all tests passed
+else
+    echo some tests failed
+fi
+
+test $ok = true
