ops

diff --git a/bin/flybox b/bin/flybox
--- a/bin/flybox
+++ b/bin/flybox
@@ -15,21 +15,84 @@ modification_timestamp() {
     stat -f "%m" "$1"
 }
 
+
+dir="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
+
+#
+# Fly ony works with amd64. This is emulated on M1/M2 macs
+#
+
+platform=linux/amd64
+
 extension="$(basename "${BASH_SOURCE[0]}")"
 tag=$(basename "${BASH_SOURCE[0]}" | tr '[:upper:]' '[:lower:]')
 tag="${tag// /_}"
-
-dir="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"
 dockerfile="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)/Dockerfile.$extension"
 
-if ! docker build -t "$tag" -f "$dockerfile" "$dir"
+build=false
+
+# build if first arg to this command is --build
+if [ $# -gt 0 -a "$1" = "--build" ]
 then
-    echo "Build failed."
-    exit 1
+    shift
+    build=true
 fi
+
+# build if this $tag has never been built
+id="$(built "$tag")"
+if [ "$id" = "" ]
+then
+    echo "building $dockerfile"
+    build=true
+fi
+
+# build if dockerfile has been modified since last build
+if [ $build != "true" ]
+then
+  built_time="$(built_timestamp "$tag")"
+  modification_time="$(modification_timestamp "$dockerfile")"
+
+  if [ $built_time -lt $modification_time ]
+  then
+      echo "rebuilding because $dockerfile changed since last build."
+      build=true
+  fi
+fi
+
+if [ $build = true ]
+then
+    if ! docker build --platform $platform --tag "$tag" --file "$dockerfile" "$dir"
+    then
+	echo "Build failed."
+	exit 1
+    fi
+fi
+
 
 CONTAINER_USER=node
 CONTAINER_HOME=/home/$CONTAINER_USER
 
-docker run -u $CONTAINER_USER -v "$HOME/.gitconfig:$CONTAINER_HOME/.gitconfig:rw" -v "$HOME/.ssh:$CONTAINER_HOME/.ssh:rw" -v "$HOME/.gnupg:$CONTAINER_HOME/.gnupg:rw" -v "$(pwd):/repo" --rm -it "$tag" bash -i
+mkdir -p "$HOME/.config"
+mkdir -p "$HOME/.gnupg"
+mkdir -p "$HOME/.ssh"
 
+
+# work with repo in container
+if ! git config --global --get-all safe.directory | grep -q "^/repo$"
+then
+  git config --global --add safe.directory /repo
+fi
+
+# get the repo base directory
+REPO="$(cd "$(git rev-parse --show-toplevel)" && pwd)"
+
+# find the working directory relative to the repo directory
+WORK="$(pwd)"
+if [ "$REPO" != "$WORK" ]
+then
+    WORK="${WORK#$REPO/}"
+else
+    WORK="."
+fi
+
+docker run --platform $platform -u 1000:1000 -v "$HOME/.config:$CONTAINER_HOME/.config" -v "$HOME/.gitconfig:$CONTAINER_HOME/.gitconfig" -v "$HOME/.ssh:$CONTAINER_HOME/.ssh" -v "$HOME/.gnupg:$CONTAINER_HOME/.gnupg" -v "$REPO:/repo" -w "/repo/$WORK" --rm -it "$tag" "$@"
